services:
  db:
    image: postgres:14
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulse
    ports:
      - "5432:5432"
    networks:
      - pulse-network
networks:
  pulse-network:
    driver: bridge
