spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pulse
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
springdoc:
  pathsToMatch: /api/v1/**, /users/**
  swagger-ui:
    use-root-path: true
